---
booktitle: Proceedings of The Algorithmic Fairness through the Lens of Causality and
  Robustness
shortname: AFCR
volume: '171'
year: '2021'
start: 2021-12-13
end: 2021-12-13
published: 2022-03-01
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: AFCR2021
month: 0
cycles: false
bibtex_editor: Schrouff, Jessica and Dieng, Awa and Rateike, Miriam and Kwegyir-Aggrey,
  Kweku and Farnadi, Golnoosh
editor:
- given: Jessica
  family: Schrouff
- given: Awa
  family: Dieng
- given: Miriam
  family: Rateike
- given: Kweku
  family: Kwegyir-Aggrey
- given: Golnoosh
  family: Farnadi
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The Algorithmic Fairness through the Lens of Causality and Robustness
    Held in Virtual on 13 December 2021

  Published as Volume 171 by the Proceedings of Machine Learning Research on 01 March 2022.

  Volume Edited by:
    Jessica Schrouff
    Awa Dieng
    Miriam Rateike
    Kweku Kwegyir-Aggrey
    Golnoosh Farnadi

  Series Editors:
    Neil D. Lawrence
date_str: 13 Dec
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v171"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v171
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v171
email: ''
conference:
  name: Algorithmic Fairness through the Lens of Causality and Robustness workshop
  url: https://www.afciworkshop.org/
  location: Virtual
  dates:
  - 2021-12-13
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v171/AFCR2021.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v171/AFCR2021.bib
